language: node_js
node_js: 8
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm test
  - npm run build

before_deploy: "echo 'ready?'"

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "rxtd-$TRAVIS_BRANCH"
  skip_cleanup: true
  acl: public_read
  region: eu-central-1
  upload-dir: dist
  # on:
  #   branch: release
  #   condition: $MY_ENV = super_awesome