System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "ts",
  typescriptOptions: {
    "module": "system",
    "noImplicitAny": true,
    "typeCheck": true,
    "tsconfig": false
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "main-bundle.js": [
      "src/main.ts",
      "npm:typescript@2.0.0/lib/lib.es6.d.ts!github:frankwallis/plugin-typescript@5.0.8/plugin.js",
      "src/enemy/sinks.ts",
      "node_modules/rxjs/Rx.js",
      "node_modules/rxjs/symbol/observable.js",
      "node_modules/rxjs/util/root.js",
      "node_modules/rxjs/symbol/iterator.js",
      "node_modules/rxjs/symbol/rxSubscriber.js",
      "node_modules/rxjs/scheduler/animationFrame.js",
      "node_modules/rxjs/scheduler/AnimationFrameScheduler.js",
      "node_modules/rxjs/scheduler/AsyncScheduler.js",
      "node_modules/rxjs/Scheduler.js",
      "node_modules/rxjs/scheduler/AnimationFrameAction.js",
      "node_modules/rxjs/util/AnimationFrame.js",
      "node_modules/rxjs/scheduler/AsyncAction.js",
      "node_modules/rxjs/scheduler/Action.js",
      "node_modules/rxjs/Subscription.js",
      "node_modules/rxjs/util/UnsubscriptionError.js",
      "node_modules/rxjs/util/errorObject.js",
      "node_modules/rxjs/util/tryCatch.js",
      "node_modules/rxjs/util/isFunction.js",
      "node_modules/rxjs/util/isObject.js",
      "node_modules/rxjs/util/isArray.js",
      "node_modules/rxjs/scheduler/queue.js",
      "node_modules/rxjs/scheduler/QueueScheduler.js",
      "node_modules/rxjs/scheduler/QueueAction.js",
      "node_modules/rxjs/scheduler/async.js",
      "node_modules/rxjs/scheduler/asap.js",
      "node_modules/rxjs/scheduler/AsapScheduler.js",
      "node_modules/rxjs/scheduler/AsapAction.js",
      "node_modules/rxjs/util/Immediate.js",
      "node_modules/rxjs/observable/dom/AjaxObservable.js",
      "node_modules/rxjs/operator/map.js",
      "node_modules/rxjs/Subscriber.js",
      "node_modules/rxjs/Observer.js",
      "node_modules/rxjs/Observable.js",
      "node_modules/rxjs/util/toSubscriber.js",
      "node_modules/rxjs/scheduler/VirtualTimeScheduler.js",
      "node_modules/rxjs/testing/TestScheduler.js",
      "node_modules/rxjs/testing/SubscriptionLog.js",
      "node_modules/rxjs/testing/HotObservable.js",
      "node_modules/rxjs/util/applyMixins.js",
      "node_modules/rxjs/testing/SubscriptionLoggable.js",
      "node_modules/rxjs/Subject.js",
      "node_modules/rxjs/SubjectSubscription.js",
      "node_modules/rxjs/util/ObjectUnsubscribedError.js",
      "node_modules/rxjs/testing/ColdObservable.js",
      "node_modules/rxjs/Notification.js",
      "node_modules/rxjs/operator/timestamp.js",
      "node_modules/rxjs/operator/timeInterval.js",
      "node_modules/rxjs/util/ArgumentOutOfRangeError.js",
      "node_modules/rxjs/util/EmptyError.js",
      "node_modules/rxjs/observable/ConnectableObservable.js",
      "node_modules/rxjs/observable/MulticastObservable.js",
      "node_modules/rxjs/BehaviorSubject.js",
      "node_modules/rxjs/ReplaySubject.js",
      "node_modules/rxjs/operator/observeOn.js",
      "node_modules/rxjs/AsyncSubject.js",
      "node_modules/rxjs/add/operator/zipAll.js",
      "node_modules/rxjs/operator/zipAll.js",
      "node_modules/rxjs/operator/zip.js",
      "node_modules/rxjs/util/subscribeToResult.js",
      "node_modules/rxjs/InnerSubscriber.js",
      "node_modules/rxjs/util/isPromise.js",
      "node_modules/rxjs/OuterSubscriber.js",
      "node_modules/rxjs/observable/ArrayObservable.js",
      "node_modules/rxjs/util/isScheduler.js",
      "node_modules/rxjs/observable/EmptyObservable.js",
      "node_modules/rxjs/observable/ScalarObservable.js",
      "node_modules/rxjs/add/operator/zip.js",
      "node_modules/rxjs/add/operator/withLatestFrom.js",
      "node_modules/rxjs/operator/withLatestFrom.js",
      "node_modules/rxjs/add/operator/windowWhen.js",
      "node_modules/rxjs/operator/windowWhen.js",
      "node_modules/rxjs/add/operator/windowToggle.js",
      "node_modules/rxjs/operator/windowToggle.js",
      "node_modules/rxjs/add/operator/windowTime.js",
      "node_modules/rxjs/operator/windowTime.js",
      "node_modules/rxjs/add/operator/windowCount.js",
      "node_modules/rxjs/operator/windowCount.js",
      "node_modules/rxjs/add/operator/window.js",
      "node_modules/rxjs/operator/window.js",
      "node_modules/rxjs/add/operator/toPromise.js",
      "node_modules/rxjs/operator/toPromise.js",
      "node_modules/rxjs/add/operator/toArray.js",
      "node_modules/rxjs/operator/toArray.js",
      "node_modules/rxjs/add/operator/timestamp.js",
      "node_modules/rxjs/add/operator/timeoutWith.js",
      "node_modules/rxjs/operator/timeoutWith.js",
      "node_modules/rxjs/util/isDate.js",
      "node_modules/rxjs/add/operator/timeout.js",
      "node_modules/rxjs/operator/timeout.js",
      "node_modules/rxjs/add/operator/timeInterval.js",
      "node_modules/rxjs/add/operator/throttleTime.js",
      "node_modules/rxjs/operator/throttleTime.js",
      "node_modules/rxjs/add/operator/throttle.js",
      "node_modules/rxjs/operator/throttle.js",
      "node_modules/rxjs/add/operator/takeWhile.js",
      "node_modules/rxjs/operator/takeWhile.js",
      "node_modules/rxjs/add/operator/takeUntil.js",
      "node_modules/rxjs/operator/takeUntil.js",
      "node_modules/rxjs/add/operator/takeLast.js",
      "node_modules/rxjs/operator/takeLast.js",
      "node_modules/rxjs/add/operator/take.js",
      "node_modules/rxjs/operator/take.js",
      "node_modules/rxjs/add/operator/switchMapTo.js",
      "node_modules/rxjs/operator/switchMapTo.js",
      "node_modules/rxjs/add/operator/switchMap.js",
      "node_modules/rxjs/operator/switchMap.js",
      "node_modules/rxjs/add/operator/switch.js",
      "node_modules/rxjs/operator/switch.js",
      "node_modules/rxjs/add/operator/subscribeOn.js",
      "node_modules/rxjs/operator/subscribeOn.js",
      "node_modules/rxjs/observable/SubscribeOnObservable.js",
      "node_modules/rxjs/util/isNumeric.js",
      "node_modules/rxjs/add/operator/startWith.js",
      "node_modules/rxjs/operator/startWith.js",
      "node_modules/rxjs/operator/concat.js",
      "node_modules/rxjs/operator/mergeAll.js",
      "node_modules/rxjs/add/operator/skipWhile.js",
      "node_modules/rxjs/operator/skipWhile.js",
      "node_modules/rxjs/add/operator/skipUntil.js",
      "node_modules/rxjs/operator/skipUntil.js",
      "node_modules/rxjs/add/operator/skip.js",
      "node_modules/rxjs/operator/skip.js",
      "node_modules/rxjs/add/operator/single.js",
      "node_modules/rxjs/operator/single.js",
      "node_modules/rxjs/add/operator/share.js",
      "node_modules/rxjs/operator/share.js",
      "node_modules/rxjs/operator/multicast.js",
      "node_modules/rxjs/add/operator/sequenceEqual.js",
      "node_modules/rxjs/operator/sequenceEqual.js",
      "node_modules/rxjs/add/operator/scan.js",
      "node_modules/rxjs/operator/scan.js",
      "node_modules/rxjs/add/operator/sampleTime.js",
      "node_modules/rxjs/operator/sampleTime.js",
      "node_modules/rxjs/add/operator/sample.js",
      "node_modules/rxjs/operator/sample.js",
      "node_modules/rxjs/add/operator/retryWhen.js",
      "node_modules/rxjs/operator/retryWhen.js",
      "node_modules/rxjs/add/operator/retry.js",
      "node_modules/rxjs/operator/retry.js",
      "node_modules/rxjs/add/operator/repeatWhen.js",
      "node_modules/rxjs/operator/repeatWhen.js",
      "node_modules/rxjs/add/operator/repeat.js",
      "node_modules/rxjs/operator/repeat.js",
      "node_modules/rxjs/add/operator/reduce.js",
      "node_modules/rxjs/operator/reduce.js",
      "node_modules/rxjs/add/operator/race.js",
      "node_modules/rxjs/operator/race.js",
      "node_modules/rxjs/add/operator/publishLast.js",
      "node_modules/rxjs/operator/publishLast.js",
      "node_modules/rxjs/add/operator/publishReplay.js",
      "node_modules/rxjs/operator/publishReplay.js",
      "node_modules/rxjs/add/operator/publishBehavior.js",
      "node_modules/rxjs/operator/publishBehavior.js",
      "node_modules/rxjs/add/operator/publish.js",
      "node_modules/rxjs/operator/publish.js",
      "node_modules/rxjs/add/operator/pluck.js",
      "node_modules/rxjs/operator/pluck.js",
      "node_modules/rxjs/add/operator/partition.js",
      "node_modules/rxjs/operator/partition.js",
      "node_modules/rxjs/operator/filter.js",
      "node_modules/rxjs/util/not.js",
      "node_modules/rxjs/add/operator/pairwise.js",
      "node_modules/rxjs/operator/pairwise.js",
      "node_modules/rxjs/add/operator/onErrorResumeNext.js",
      "node_modules/rxjs/operator/onErrorResumeNext.js",
      "node_modules/rxjs/observable/FromObservable.js",
      "node_modules/rxjs/observable/ArrayLikeObservable.js",
      "node_modules/rxjs/observable/IteratorObservable.js",
      "node_modules/rxjs/observable/PromiseObservable.js",
      "node_modules/rxjs/add/operator/observeOn.js",
      "node_modules/rxjs/add/operator/multicast.js",
      "node_modules/rxjs/add/operator/min.js",
      "node_modules/rxjs/operator/min.js",
      "node_modules/rxjs/add/operator/mergeScan.js",
      "node_modules/rxjs/operator/mergeScan.js",
      "node_modules/rxjs/add/operator/mergeMapTo.js",
      "node_modules/rxjs/operator/mergeMapTo.js",
      "node_modules/rxjs/add/operator/mergeMap.js",
      "node_modules/rxjs/operator/mergeMap.js",
      "node_modules/rxjs/add/operator/mergeAll.js",
      "node_modules/rxjs/add/operator/merge.js",
      "node_modules/rxjs/operator/merge.js",
      "node_modules/rxjs/add/operator/max.js",
      "node_modules/rxjs/operator/max.js",
      "node_modules/rxjs/add/operator/materialize.js",
      "node_modules/rxjs/operator/materialize.js",
      "node_modules/rxjs/add/operator/mapTo.js",
      "node_modules/rxjs/operator/mapTo.js",
      "node_modules/rxjs/add/operator/map.js",
      "node_modules/rxjs/add/operator/every.js",
      "node_modules/rxjs/operator/every.js",
      "node_modules/rxjs/add/operator/let.js",
      "node_modules/rxjs/operator/let.js",
      "node_modules/rxjs/add/operator/last.js",
      "node_modules/rxjs/operator/last.js",
      "node_modules/rxjs/add/operator/auditTime.js",
      "node_modules/rxjs/operator/auditTime.js",
      "node_modules/rxjs/add/operator/audit.js",
      "node_modules/rxjs/operator/audit.js",
      "node_modules/rxjs/add/operator/isEmpty.js",
      "node_modules/rxjs/operator/isEmpty.js",
      "node_modules/rxjs/add/operator/ignoreElements.js",
      "node_modules/rxjs/operator/ignoreElements.js",
      "node_modules/rxjs/util/noop.js",
      "node_modules/rxjs/add/operator/groupBy.js",
      "node_modules/rxjs/operator/groupBy.js",
      "node_modules/rxjs/util/FastMap.js",
      "node_modules/rxjs/util/Map.js",
      "node_modules/rxjs/util/MapPolyfill.js",
      "node_modules/rxjs/add/operator/first.js",
      "node_modules/rxjs/operator/first.js",
      "node_modules/rxjs/add/operator/findIndex.js",
      "node_modules/rxjs/operator/findIndex.js",
      "node_modules/rxjs/operator/find.js",
      "node_modules/rxjs/add/operator/find.js",
      "node_modules/rxjs/add/operator/finally.js",
      "node_modules/rxjs/operator/finally.js",
      "node_modules/rxjs/add/operator/filter.js",
      "node_modules/rxjs/add/operator/elementAt.js",
      "node_modules/rxjs/operator/elementAt.js",
      "node_modules/rxjs/add/operator/expand.js",
      "node_modules/rxjs/operator/expand.js",
      "node_modules/rxjs/add/operator/exhaustMap.js",
      "node_modules/rxjs/operator/exhaustMap.js",
      "node_modules/rxjs/add/operator/exhaust.js",
      "node_modules/rxjs/operator/exhaust.js",
      "node_modules/rxjs/add/operator/do.js",
      "node_modules/rxjs/operator/do.js",
      "node_modules/rxjs/add/operator/distinctUntilKeyChanged.js",
      "node_modules/rxjs/operator/distinctUntilKeyChanged.js",
      "node_modules/rxjs/operator/distinctUntilChanged.js",
      "node_modules/rxjs/add/operator/distinctUntilChanged.js",
      "node_modules/rxjs/add/operator/distinctKey.js",
      "node_modules/rxjs/operator/distinctKey.js",
      "node_modules/rxjs/operator/distinct.js",
      "node_modules/rxjs/add/operator/distinct.js",
      "node_modules/rxjs/add/operator/delayWhen.js",
      "node_modules/rxjs/operator/delayWhen.js",
      "node_modules/rxjs/add/operator/delay.js",
      "node_modules/rxjs/operator/delay.js",
      "node_modules/rxjs/add/operator/defaultIfEmpty.js",
      "node_modules/rxjs/operator/defaultIfEmpty.js",
      "node_modules/rxjs/add/operator/debounceTime.js",
      "node_modules/rxjs/operator/debounceTime.js",
      "node_modules/rxjs/add/operator/debounce.js",
      "node_modules/rxjs/operator/debounce.js",
      "node_modules/rxjs/add/operator/dematerialize.js",
      "node_modules/rxjs/operator/dematerialize.js",
      "node_modules/rxjs/add/operator/count.js",
      "node_modules/rxjs/operator/count.js",
      "node_modules/rxjs/add/operator/concatMapTo.js",
      "node_modules/rxjs/operator/concatMapTo.js",
      "node_modules/rxjs/add/operator/concatMap.js",
      "node_modules/rxjs/operator/concatMap.js",
      "node_modules/rxjs/add/operator/concatAll.js",
      "node_modules/rxjs/operator/concatAll.js",
      "node_modules/rxjs/add/operator/concat.js",
      "node_modules/rxjs/add/operator/combineLatest.js",
      "node_modules/rxjs/operator/combineLatest.js",
      "node_modules/rxjs/add/operator/combineAll.js",
      "node_modules/rxjs/operator/combineAll.js",
      "node_modules/rxjs/add/operator/catch.js",
      "node_modules/rxjs/operator/catch.js",
      "node_modules/rxjs/add/operator/cache.js",
      "node_modules/rxjs/operator/cache.js",
      "node_modules/rxjs/add/operator/bufferWhen.js",
      "node_modules/rxjs/operator/bufferWhen.js",
      "node_modules/rxjs/add/operator/bufferToggle.js",
      "node_modules/rxjs/operator/bufferToggle.js",
      "node_modules/rxjs/add/operator/bufferTime.js",
      "node_modules/rxjs/operator/bufferTime.js",
      "node_modules/rxjs/add/operator/bufferCount.js",
      "node_modules/rxjs/operator/bufferCount.js",
      "node_modules/rxjs/add/operator/buffer.js",
      "node_modules/rxjs/operator/buffer.js",
      "node_modules/rxjs/add/observable/dom/webSocket.js",
      "node_modules/rxjs/observable/dom/webSocket.js",
      "node_modules/rxjs/observable/dom/WebSocketSubject.js",
      "node_modules/rxjs/util/assign.js",
      "node_modules/rxjs/add/observable/dom/ajax.js",
      "node_modules/rxjs/observable/dom/ajax.js",
      "node_modules/rxjs/add/observable/zip.js",
      "node_modules/rxjs/observable/zip.js",
      "node_modules/rxjs/add/observable/timer.js",
      "node_modules/rxjs/observable/timer.js",
      "node_modules/rxjs/observable/TimerObservable.js",
      "node_modules/rxjs/add/observable/throw.js",
      "node_modules/rxjs/observable/throw.js",
      "node_modules/rxjs/observable/ErrorObservable.js",
      "node_modules/rxjs/add/observable/using.js",
      "node_modules/rxjs/observable/using.js",
      "node_modules/rxjs/observable/UsingObservable.js",
      "node_modules/rxjs/add/observable/range.js",
      "node_modules/rxjs/observable/range.js",
      "node_modules/rxjs/observable/RangeObservable.js",
      "node_modules/rxjs/add/observable/pairs.js",
      "node_modules/rxjs/observable/pairs.js",
      "node_modules/rxjs/observable/PairsObservable.js",
      "node_modules/rxjs/add/observable/onErrorResumeNext.js",
      "node_modules/rxjs/add/observable/of.js",
      "node_modules/rxjs/observable/of.js",
      "node_modules/rxjs/add/observable/never.js",
      "node_modules/rxjs/observable/never.js",
      "node_modules/rxjs/observable/NeverObservable.js",
      "node_modules/rxjs/add/observable/race.js",
      "node_modules/rxjs/add/observable/merge.js",
      "node_modules/rxjs/observable/merge.js",
      "node_modules/rxjs/add/observable/interval.js",
      "node_modules/rxjs/observable/interval.js",
      "node_modules/rxjs/observable/IntervalObservable.js",
      "node_modules/rxjs/add/observable/if.js",
      "node_modules/rxjs/observable/if.js",
      "node_modules/rxjs/observable/IfObservable.js",
      "node_modules/rxjs/add/observable/generate.js",
      "node_modules/rxjs/observable/GenerateObservable.js",
      "node_modules/rxjs/add/observable/fromPromise.js",
      "node_modules/rxjs/observable/fromPromise.js",
      "node_modules/rxjs/add/observable/fromEventPattern.js",
      "node_modules/rxjs/observable/fromEventPattern.js",
      "node_modules/rxjs/observable/FromEventPatternObservable.js",
      "node_modules/rxjs/add/observable/fromEvent.js",
      "node_modules/rxjs/observable/fromEvent.js",
      "node_modules/rxjs/observable/FromEventObservable.js",
      "node_modules/rxjs/add/observable/from.js",
      "node_modules/rxjs/observable/from.js",
      "node_modules/rxjs/add/observable/forkJoin.js",
      "node_modules/rxjs/observable/forkJoin.js",
      "node_modules/rxjs/observable/ForkJoinObservable.js",
      "node_modules/rxjs/add/observable/empty.js",
      "node_modules/rxjs/observable/empty.js",
      "node_modules/rxjs/add/observable/defer.js",
      "node_modules/rxjs/observable/defer.js",
      "node_modules/rxjs/observable/DeferObservable.js",
      "node_modules/rxjs/add/observable/concat.js",
      "node_modules/rxjs/observable/concat.js",
      "node_modules/rxjs/add/observable/combineLatest.js",
      "node_modules/rxjs/observable/combineLatest.js",
      "node_modules/rxjs/add/observable/bindNodeCallback.js",
      "node_modules/rxjs/observable/bindNodeCallback.js",
      "node_modules/rxjs/observable/BoundNodeCallbackObservable.js",
      "node_modules/rxjs/add/observable/bindCallback.js",
      "node_modules/rxjs/observable/bindCallback.js",
      "node_modules/rxjs/observable/BoundCallbackObservable.js",
      "src/enemy/enemy.ts",
      "src/settings.ts",
      "src/utils.ts",
      "npm:victor@1.1.0.js",
      "npm:victor@1.1.0/index.js",
      "src/mapPoint.ts",
      "src/ticker.ts",
      "src/menu/sinks.ts",
      "src/stage/stage.ts",
      "github:CreateJS/EaselJS@0.8.2.js",
      "github:CreateJS/EaselJS@0.8.2/lib/easeljs-0.8.2.combined.js",
      "src/bullet/sinks.ts",
      "src/tower/sinks.ts",
      "src/wallet/sinks.ts",
      "src/bullet/index.ts",
      "src/bullet/effects.ts",
      "src/bullet/drivers.ts",
      "src/bullet/bullet.ts",
      "src/enemy/index.ts",
      "src/tower/index.ts",
      "src/tower/effects.ts",
      "src/tower/shape.ts",
      "src/tower/area.ts",
      "src/tower/towers.ts",
      "src/scenario.ts",
      "src/menu/index.ts",
      "src/menu/effects.ts",
      "src/menu/drivers.ts",
      "src/wallet/index.ts",
      "src/wallet/drivers.ts",
      "src/path.ts"
    ]
  },

  packages: {
    "src": {
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    }
  },

  map: {
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "bootstrap": "github:kristopolous/BOOTSTRA.386@master",
    "core-js": "npm:core-js@1.2.7",
    "css": "github:systemjs/plugin-css@0.1.26",
    "easel": "github:CreateJS/EaselJS@0.8.2",
    "node-easel": "npm:node-easel@0.1.2",
    "ramda": "npm:ramda@0.22.1",
    "rxjs": "node_modules/rxjs",
    "ts": "github:frankwallis/plugin-typescript@5.0.8",
    "ts-runtime": "npm:babel-runtime@5.8.38",
    "tween.js": "npm:tween.js@16.3.4",
    "victor": "npm:victor@1.1.0",
    "github:frankwallis/plugin-typescript@5.0.8": {
      "typescript": "npm:typescript@2.0.0"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.8"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:asn1.js@4.8.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.11.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:bn.js@4.11.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.11.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.11.5",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.3.1",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:canvas@1.4.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "nan": "npm:nan@2.4.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@1.2.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.11.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.3.1"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.5"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.11.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:elliptic@6.3.1": {
      "bn.js": "npm:bn.js@4.11.5",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.11.5",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:nan@2.4.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:node-easel@0.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "canvas": "npm:canvas@1.4.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.8.0",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:process@0.11.8": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.11.5",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:ramda@0.22.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:randombytes@2.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:typescript@2.0.0": {
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  }
});
